name: CI

on:
  push:
    branches: ["develop", "main"]
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  LACHAIN_EXPLORER_API_URL: https://explorer-api.lachain.network/api
  LACHAIN_EXPLORER_URL: https://explorer.lachain.network
  LACHAIN_RPC_URL: https://rpc1.mainnet.lachain.network
  LATESTNET_EXPLORER_API_URL: https://testexplorer-api.lachain.network/api
  LATESTNET_EXPLORER_URL: https://testexplorer.lachain.network
  LATESTNET_RPC_URL: https://rpc.testnet.lachain.network

jobs:
  lint:
    runs-on: ubuntu-latest
    container: node:20-buster
    steps:
      - uses: actions/checkout@v3
      - name: Cache npm
        uses: actions/cache@v3
        with:
          path: |
            ~/cache
            !~/cache/exclude
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      # Install deps
      - name: Install deps
        run: npm ci
      # Run linter
      - name: Run linter
        run: npm run lint:check
      # Run Prettier
      - name: Run prettier
        run: npm run format:check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Cache npm
        uses: actions/cache@v3
        with:
          path: |
            ~/cache
            !~/cache/exclude
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      # Install deps
      - name: Install deps
        run: npm ci
      # run tests
      - name: Run Test
        run: npm run test

  slither:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3
      # Step 2: Install Node.js (version 20)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      # Step 3: Install NPM dependencies
      - name: Install NPM dependencies
        run: npm install
      # Step 4: Set up Python (version 3.11)
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      # Step 5: Install Slither and solc-select
      - name: Install Slither and solc-select
        run: |
          pip3 install slither-analyzer
          pip3 install solc-select
      # Step 6: Install Solidity compiler 0.8.4 and set as default
      - name: Install Solidity 0.8.4
        run: |
          solc-select install 0.8.4
          solc-select use 0.8.4
      # Step 7: Run Slither analysis
      - name: Run Slither
        run: slither . --filter-paths "node_modules" --disable-color --print human-summary
